/**
 * src/lib/contentData.ts
 * In-memory unified content store pre-populated with relational Track → Course → Module → Lesson → Activity hierarchy
 */

import {
  Track,
  Course,
  Module,
  Lesson,
  Activity,
  LearningResource,
  Assessment,
  LearningProgress,
} from "@/types/content";

// ─── Resources Store ─────────────────────────────────────────────────────────

export const MOCK_RESOURCES: LearningResource[] = [
  {
    id: "res-1",
    title: "Python Cheat Sheet PDF",
    description: "Complete 2-page quick reference guide for Python 3 syntax & standard library.",
    type: "pdf",
    url: "https://assets.qbitx.com/resources/python-cheatsheet.pdf",
    fileSizeBytes: 1048576,
    mimeType: "application/pdf",
    isDownloadable: true,
    createdBy: "usr-admin-1",
    createdAt: "2026-01-10T10:00:00Z",
  },
  {
    id: "res-2",
    title: "Binary Tree Visualizer Repository",
    description: "Interactive React repository demonstrating binary search tree balancing.",
    type: "github_repo",
    url: "https://github.com/qbitx-labs/bst-visualizer",
    isDownloadable: false,
    createdBy: "usr-mentor-1",
    createdAt: "2026-01-15T12:00:00Z",
  },
  {
    id: "res-3",
    title: "RAG Pipeline Starter Kit",
    description: "FastAPI + LangChain + Supabase Vector starter code package.",
    type: "zip",
    url: "https://assets.qbitx.com/templates/rag-starter.zip",
    fileSizeBytes: 4194304,
    mimeType: "application/zip",
    isDownloadable: true,
    createdBy: "usr-mentor-2",
    createdAt: "2026-02-01T14:30:00Z",
  },
];

// ─── Assessments Store ───────────────────────────────────────────────────────

export const MOCK_ASSESSMENTS: Assessment[] = [
  {
    id: "ass-1",
    title: "Loops & Conditions Quiz",
    description: "Assess your understanding of while loops, for loops, and nested branching.",
    type: "quiz",
    maxAttempts: 3,
    gradingMethod: "auto",
    passingScorePercentage: 80,
    instructions: "Answer all 10 multiple-choice questions within 15 minutes.",
  },
  {
    id: "ass-2",
    title: "Binary Tree Traversal Coding Lab",
    description: "Implement inorder, preorder, and postorder traversal functions in Python.",
    type: "coding_challenge",
    maxAttempts: 5,
    gradingMethod: "auto",
    passingScorePercentage: 90,
    instructions: "Write clean Python code matching the test assertions in the environment.",
  },
  {
    id: "ass-3",
    title: "RAG Architecture Project Submission",
    description: "Submit your Github repository link and architecture diagram PDF.",
    type: "assignment",
    maxAttempts: 2,
    gradingMethod: "mentor",
    passingScorePercentage: 85,
    deadline: "2026-08-15T23:59:59Z",
    rubric: [
      { id: "r1", criterion: "Code Quality & Clean Architecture", maxPoints: 40 },
      { id: "r2", criterion: "RAG Retrieval Accuracy", maxPoints: 30 },
      { id: "r3", criterion: "Documentation & Readme", maxPoints: 30 },
    ],
    instructions: "Ensure your project includes a docker-compose file and clear setup steps.",
  },
];

// ─── Activities Store ────────────────────────────────────────────────────────

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: "act-1",
    lessonId: "les-1",
    orderIndex: 1,
    type: "video",
    metadata: {
      id: "act-1",
      slug: "intro-to-python-video",
      title: "Welcome to Python Programming",
      description: "Overview of Python ecosystem, installation, and setup.",
      tags: ["python", "setup", "intro"],
      category: "Programming Fundamentals",
      difficulty: "beginner",
      estimatedDurationMinutes: 15,
      language: "en",
      visibility: "public",
      status: "published",
      version: "1.0.0",
      createdBy: "usr-mentor-1",
      updatedBy: "usr-mentor-1",
      publishedAt: "2026-01-10T10:00:00Z",
      createdAt: "2026-01-10T10:00:00Z",
      updatedAt: "2026-01-10T10:00:00Z",
      isArchived: false,
    },
    contentPayload: {
      videoUrl: "https://www.youtube.com/embed/kqtD5dpn9C8",
    },
    resourceIds: ["res-1"],
  },
  {
    id: "act-2",
    lessonId: "les-1",
    orderIndex: 2,
    type: "quiz",
    metadata: {
      id: "act-2",
      slug: "intro-to-python-quiz",
      title: "Basic Concepts Checkup",
      description: "Quick 5-question checkup on Python setup.",
      tags: ["quiz", "basics"],
      category: "Programming Fundamentals",
      difficulty: "beginner",
      estimatedDurationMinutes: 10,
      language: "en",
      visibility: "enrolled_only",
      status: "published",
      version: "1.0.0",
      createdBy: "usr-mentor-1",
      updatedBy: "usr-mentor-1",
      createdAt: "2026-01-10T10:30:00Z",
      updatedAt: "2026-01-10T10:30:00Z",
      isArchived: false,
    },
    contentPayload: {
      quizData: {
        questionsCount: 5,
        timeLimitMinutes: 10,
      },
    },
    assessmentId: "ass-1",
    resourceIds: [],
  },
  {
    id: "act-3",
    lessonId: "les-2",
    orderIndex: 1,
    type: "coding_lab",
    metadata: {
      id: "act-3",
      slug: "bst-traversal-lab",
      title: "Coding Lab: Binary Search Tree",
      description: "Interactive coding environment for tree traversal algorithms.",
      tags: ["dsa", "trees", "python"],
      category: "CS Fundamentals",
      difficulty: "intermediate",
      estimatedDurationMinutes: 45,
      language: "en",
      visibility: "enrolled_only",
      status: "published",
      version: "1.2.0",
      createdBy: "usr-mentor-2",
      updatedBy: "usr-mentor-2",
      createdAt: "2026-01-15T09:00:00Z",
      updatedAt: "2026-01-15T09:00:00Z",
      isArchived: false,
    },
    contentPayload: {
      starterCode: "class Node:\n    def __init__(self, val):\n        self.val = val\n        self.left = None\n        self.right = None\n\ndef inorder_traversal(root):\n    # Write your implementation here\n    pass",
    },
    assessmentId: "ass-2",
    resourceIds: ["res-2"],
  },
  {
    id: "act-4",
    lessonId: "les-3",
    orderIndex: 1,
    type: "project",
    metadata: {
      id: "act-4",
      slug: "rag-pipeline-project",
      title: "Capstone: Production RAG System",
      description: "Build an end-to-end vector search & LLM response pipeline.",
      tags: ["ai", "rag", "fastapi", "langchain"],
      category: "AI Engineering",
      difficulty: "advanced",
      estimatedDurationMinutes: 120,
      language: "en",
      visibility: "enrolled_only",
      status: "published",
      version: "2.0.0",
      createdBy: "usr-mentor-2",
      updatedBy: "usr-mentor-2",
      createdAt: "2026-02-01T10:00:00Z",
      updatedAt: "2026-02-01T10:00:00Z",
      isArchived: false,
    },
    contentPayload: {
      projectInstructions: "Full spec details at qbitx.com/specs/rag-capstone",
    },
    assessmentId: "ass-3",
    resourceIds: ["res-3"],
  },
];

// ─── Lessons Store ───────────────────────────────────────────────────────────

export const MOCK_LESSONS: Lesson[] = [
  {
    id: "les-1",
    moduleId: "mod-1",
    orderIndex: 1,
    metadata: {
      id: "les-1",
      slug: "getting-started-with-python",
      title: "Lesson 1: Getting Started with Python",
      subtitle: "Syntax, Variables & Data Types",
      description: "Master foundational Python syntax, variables, and primitive data types.",
      thumbnail: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?auto=format&fit=crop&q=80&w=600",
      tags: ["python", "variables", "basics"],
      category: "Programming Fundamentals",
      difficulty: "beginner",
      estimatedDurationMinutes: 25,
      language: "en",
      visibility: "public",
      status: "published",
      version: "1.0.0",
      createdBy: "usr-mentor-1",
      updatedBy: "usr-mentor-1",
      publishedAt: "2026-01-10T10:00:00Z",
      createdAt: "2026-01-10T10:00:00Z",
      updatedAt: "2026-01-10T10:00:00Z",
      isArchived: false,
    },
    aiMetadata: {
      learningObjectives: [
        "Understand Python syntax rules",
        "Declare and use variables",
        "Differentiate between integers, floats, strings, and booleans",
      ],
      skillsTaught: ["Python 3", "Basic I/O", "Variable Declaration"],
      prerequisites: [],
      keywords: ["python", "variables", "print", "data types"],
      difficultyScore: 15,
      bloomsTaxonomyLevel: "understand",
      estimatedLearningMinutes: 25,
      relatedLessonIds: [],
      suggestedNextLessonIds: ["les-2"],
    },
    permissions: {
      ownerId: "usr-mentor-1",
      editorIds: ["usr-mentor-1"],
      reviewerIds: ["usr-admin-1"],
      mentorAccess: true,
      studentAccess: true,
      adminAccess: true,
    },
    activityIds: ["act-1", "act-2"],
    resourceIds: ["res-1"],
    assessmentIds: ["ass-1"],
  },
  {
    id: "les-2",
    moduleId: "mod-2",
    orderIndex: 1,
    metadata: {
      id: "les-2",
      slug: "binary-search-trees-deep-dive",
      title: "Lesson 2: Binary Search Tree Traversals",
      subtitle: "Inorder, Preorder, and Postorder Algorithms",
      description: "Deep dive into recursive tree traversals with visualization and live code execution.",
      thumbnail: "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&q=80&w=600",
      tags: ["dsa", "trees", "algorithms"],
      category: "CS Fundamentals",
      difficulty: "intermediate",
      estimatedDurationMinutes: 45,
      language: "en",
      visibility: "enrolled_only",
      status: "published",
      version: "1.1.0",
      createdBy: "usr-mentor-2",
      updatedBy: "usr-mentor-2",
      publishedAt: "2026-01-15T09:00:00Z",
      createdAt: "2026-01-15T09:00:00Z",
      updatedAt: "2026-01-15T09:00:00Z",
      isArchived: false,
    },
    aiMetadata: {
      learningObjectives: [
        "Implement recursive tree traversals",
        "Analyze time complexity O(N)",
        "Use BST properties for fast search",
      ],
      skillsTaught: ["Data Structures", "Recursion", "Big-O Analysis"],
      prerequisites: ["les-1"],
      keywords: ["binary tree", "bst", "inorder", "preorder", "recursion"],
      difficultyScore: 55,
      bloomsTaxonomyLevel: "apply",
      estimatedLearningMinutes: 45,
      relatedLessonIds: ["les-1"],
      suggestedNextLessonIds: ["les-3"],
    },
    permissions: {
      ownerId: "usr-mentor-2",
      editorIds: ["usr-mentor-2"],
      reviewerIds: ["usr-admin-1"],
      mentorAccess: true,
      studentAccess: true,
      adminAccess: true,
    },
    activityIds: ["act-3"],
    resourceIds: ["res-2"],
    assessmentIds: ["ass-2"],
  },
  {
    id: "les-3",
    moduleId: "mod-3",
    orderIndex: 1,
    metadata: {
      id: "les-3",
      slug: "building-rag-pipelines",
      title: "Lesson 3: Building Production RAG Pipelines",
      subtitle: "Vector Search, Embeddings & LLM Integration",
      description: "Architect and deploy end-to-end Retrieval-Augmented Generation workflows using QbitX stack.",
      thumbnail: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?auto=format&fit=crop&q=80&w=600",
      tags: ["ai", "rag", "langchain", "vector-search"],
      category: "AI Engineering",
      difficulty: "advanced",
      estimatedDurationMinutes: 120,
      language: "en",
      visibility: "enrolled_only",
      status: "published",
      version: "2.0.0",
      createdBy: "usr-mentor-2",
      updatedBy: "usr-mentor-2",
      publishedAt: "2026-02-01T10:00:00Z",
      createdAt: "2026-02-01T10:00:00Z",
      updatedAt: "2026-02-01T10:00:00Z",
      isArchived: false,
    },
    aiMetadata: {
      learningObjectives: [
        "Generate vector embeddings",
        "Perform similarity search in PostgreSQL / Supabase Vector",
        "Chain prompt context to OpenAI / Gemini LLMs",
      ],
      skillsTaught: ["RAG Architecture", "Vector DBs", "LLM Prompting", "FastAPI"],
      prerequisites: ["les-1", "les-2"],
      keywords: ["rag", "llm", "embeddings", "vector search", "langchain"],
      difficultyScore: 85,
      bloomsTaxonomyLevel: "create",
      estimatedLearningMinutes: 120,
      relatedLessonIds: ["les-2"],
      suggestedNextLessonIds: [],
    },
    permissions: {
      ownerId: "usr-mentor-2",
      editorIds: ["usr-mentor-2"],
      reviewerIds: ["usr-admin-1"],
      mentorAccess: true,
      studentAccess: true,
      adminAccess: true,
    },
    activityIds: ["act-4"],
    resourceIds: ["res-3"],
    assessmentIds: ["ass-3"],
  },
];

// ─── Modules Store ───────────────────────────────────────────────────────────

export const MOCK_MODULES: Module[] = [
  {
    id: "mod-1",
    courseId: "crs-1",
    orderIndex: 1,
    metadata: {
      id: "mod-1",
      slug: "module-1-python-foundations",
      title: "Module 1: Python Foundations",
      subtitle: "Core Syntax, Control Flow & Functions",
      description: "Master basic programming concepts with hands-on exercises.",
      tags: ["python", "foundations"],
      category: "Programming Fundamentals",
      difficulty: "beginner",
      estimatedDurationMinutes: 120,
      language: "en",
      visibility: "public",
      status: "published",
      version: "1.0.0",
      createdBy: "usr-mentor-1",
      updatedBy: "usr-mentor-1",
      createdAt: "2026-01-10T10:00:00Z",
      updatedAt: "2026-01-10T10:00:00Z",
      isArchived: false,
    },
    lessonIds: ["les-1"],
    completionRules: [
      {
        id: "cr-1",
        type: "complete_all_lessons",
        title: "Finish All Lessons in Module 1",
        description: "Complete every lesson and pass basic quizzes.",
        requiresMentorApproval: false,
      },
    ],
  },
  {
    id: "mod-2",
    courseId: "crs-1",
    orderIndex: 2,
    metadata: {
      id: "mod-2",
      slug: "module-2-data-structures",
      title: "Module 2: Data Structures & Trees",
      subtitle: "Arrays, Linked Lists, Graphs & BSTs",
      description: "Build linear and non-linear data structures from scratch.",
      tags: ["dsa", "data-structures"],
      category: "CS Fundamentals",
      difficulty: "intermediate",
      estimatedDurationMinutes: 180,
      language: "en",
      visibility: "enrolled_only",
      status: "published",
      version: "1.1.0",
      createdBy: "usr-mentor-2",
      updatedBy: "usr-mentor-2",
      createdAt: "2026-01-15T09:00:00Z",
      updatedAt: "2026-01-15T09:00:00Z",
      isArchived: false,
    },
    lessonIds: ["les-2"],
    completionRules: [
      {
        id: "cr-2",
        type: "pass_all_quizzes",
        title: "Pass Binary Search Tree Coding Lab",
        description: "Achieve at least 90% score on the tree traversal coding challenge.",
        requiredAssessmentIds: ["ass-2"],
        requiresMentorApproval: false,
      },
    ],
  },
  {
    id: "mod-3",
    courseId: "crs-2",
    orderIndex: 1,
    metadata: {
      id: "mod-3",
      slug: "module-3-ai-engineering",
      title: "Module 3: Full-Stack AI & RAG Engineering",
      subtitle: "Vector DBs, FastAPI & Next.js Integration",
      description: "Build and deploy production-ready AI pipelines.",
      tags: ["ai", "rag", "fullstack"],
      category: "AI Engineering",
      difficulty: "advanced",
      estimatedDurationMinutes: 240,
      language: "en",
      visibility: "enrolled_only",
      status: "published",
      version: "2.0.0",
      createdBy: "usr-mentor-2",
      updatedBy: "usr-mentor-2",
      createdAt: "2026-02-01T10:00:00Z",
      updatedAt: "2026-02-01T10:00:00Z",
      isArchived: false,
    },
    lessonIds: ["les-3"],
    completionRules: [
      {
        id: "cr-3",
        type: "mentor_approval",
        title: "Mentor Project Sign-off",
        description: "Receive passing grade from mentor on RAG Capstone submission.",
        requiredAssessmentIds: ["ass-3"],
        requiresMentorApproval: true,
      },
    ],
  },
];

// ─── Courses Store ───────────────────────────────────────────────────────────

export const MOCK_COURSES: Course[] = [
  {
    id: "crs-1",
    trackId: "trk-1",
    metadata: {
      id: "crs-1",
      slug: "intro-to-programming-and-dsa",
      title: "Introduction to Programming & Data Structures",
      subtitle: "Master Python 3, Recursion & Core Computer Science",
      description: "A comprehensive course taking students from zero coding experience to algorithmic mastery.",
      thumbnail: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800",
      coverImage: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80&w=1600",
      icon: "code",
      tags: ["python", "dsa", "programming", "cs"],
      category: "CS Fundamentals",
      difficulty: "beginner",
      estimatedDurationMinutes: 300,
      language: "en",
      visibility: "public",
      status: "published",
      version: "1.0.0",
      createdBy: "usr-mentor-1",
      updatedBy: "usr-mentor-1",
      publishedAt: "2026-01-10T10:00:00Z",
      createdAt: "2026-01-10T10:00:00Z",
      updatedAt: "2026-01-10T10:00:00Z",
      isArchived: false,
    },
    aiMetadata: {
      learningObjectives: [
        "Write clean procedural and object-oriented Python code",
        "Implement fundamental data structures from scratch",
        "Analyze algorithm complexity using Big-O notation",
      ],
      skillsTaught: ["Python", "Algorithms", "Data Structures", "Problem Solving"],
      prerequisites: [],
      keywords: ["python", "dsa", "trees", "recursion", "big-o"],
      difficultyScore: 35,
      bloomsTaxonomyLevel: "apply",
      estimatedLearningMinutes: 300,
      relatedLessonIds: ["les-1", "les-2"],
      suggestedNextLessonIds: ["les-3"],
    },
    permissions: {
      ownerId: "usr-mentor-1",
      editorIds: ["usr-mentor-1", "usr-mentor-2"],
      reviewerIds: ["usr-admin-1"],
      mentorAccess: true,
      studentAccess: true,
      adminAccess: true,
    },
    moduleIds: ["mod-1", "mod-2"],
    certificateTemplateId: "cert-tmpl-py-dsa",
    completionRules: [
      {
        id: "cr-crs-1",
        type: "complete_all_lessons",
        title: "Complete All Course Modules",
        description: "Finish Module 1 and Module 2 to earn certificate.",
        requiresMentorApproval: false,
      },
    ],
  },
  {
    id: "crs-2",
    trackId: "trk-1",
    metadata: {
      id: "crs-2",
      slug: "full-stack-ai-engineering",
      title: "Full-Stack AI Web Engineering",
      subtitle: "Build Next.js 16 SaaS Apps with RAG & LLM Integration",
      description: "Advanced project-based course teaching modern AI software architecture.",
      thumbnail: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?auto=format&fit=crop&q=80&w=800",
      coverImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=1600",
      icon: "cpu",
      tags: ["ai", "rag", "nextjs", "fastapi", "fullstack"],
      category: "AI Engineering",
      difficulty: "advanced",
      estimatedDurationMinutes: 480,
      language: "en",
      visibility: "enrolled_only",
      status: "published",
      version: "2.0.0",
      createdBy: "usr-mentor-2",
      updatedBy: "usr-mentor-2",
      publishedAt: "2026-02-01T10:00:00Z",
      createdAt: "2026-02-01T10:00:00Z",
      updatedAt: "2026-02-01T10:00:00Z",
      isArchived: false,
    },
    aiMetadata: {
      learningObjectives: [
        "Architect scalable RAG systems with FastAPI and Next.js 16",
        "Perform vector embeddings search with Supabase Vector",
        "Deploy containerized AI microservices on cloud infrastructure",
      ],
      skillsTaught: ["Next.js 16", "FastAPI", "Vector Search", "RAG Pipelines", "Docker"],
      prerequisites: ["crs-1"],
      keywords: ["ai", "rag", "nextjs", "fastapi", "embeddings", "vector"],
      difficultyScore: 85,
      bloomsTaxonomyLevel: "create",
      estimatedLearningMinutes: 480,
      relatedLessonIds: ["les-3"],
      suggestedNextLessonIds: [],
    },
    permissions: {
      ownerId: "usr-mentor-2",
      editorIds: ["usr-mentor-2"],
      reviewerIds: ["usr-admin-1"],
      mentorAccess: true,
      studentAccess: true,
      adminAccess: true,
    },
    moduleIds: ["mod-3"],
    certificateTemplateId: "cert-tmpl-ai-eng",
    completionRules: [
      {
        id: "cr-crs-2",
        type: "mentor_approval",
        title: "Complete Capstone Project",
        description: "Submit RAG Capstone and receive mentor approval.",
        requiresMentorApproval: true,
      },
    ],
  },
];

// ─── Tracks Store ────────────────────────────────────────────────────────────

export const MOCK_TRACKS: Track[] = [
  {
    id: "trk-1",
    metadata: {
      id: "trk-1",
      slug: "software-engineering-career-track",
      title: "Software Engineering & AI Career Track",
      subtitle: "From Fundamentals to Production AI Web Architecture",
      description: "The official QbitX flagship career pathway preparing students for junior to mid-level software engineering roles.",
      thumbnail: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80&w=800",
      coverImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=1600",
      icon: "terminal",
      tags: ["career-track", "software-engineering", "fullstack", "ai"],
      category: "Career Pathway",
      difficulty: "intermediate",
      estimatedDurationMinutes: 780,
      language: "en",
      visibility: "public",
      status: "published",
      version: "1.0.0",
      createdBy: "usr-admin-1",
      updatedBy: "usr-admin-1",
      publishedAt: "2026-01-01T00:00:00Z",
      createdAt: "2026-01-01T00:00:00Z",
      updatedAt: "2026-01-01T00:00:00Z",
      isArchived: false,
    },
    aiMetadata: {
      learningObjectives: [
        "Master procedural, object-oriented, and algorithmic programming",
        "Architect modern full-stack web applications with Next.js & Supabase",
        "Deploy production RAG and LLM features",
      ],
      skillsTaught: [
        "Python",
        "Data Structures",
        "TypeScript",
        "Next.js 16",
        "FastAPI",
        "RAG Engineering",
      ],
      prerequisites: [],
      keywords: ["career track", "software engineer", "fullstack", "ai"],
      difficultyScore: 60,
      bloomsTaxonomyLevel: "create",
      estimatedLearningMinutes: 780,
      relatedLessonIds: ["les-1", "les-2", "les-3"],
      suggestedNextLessonIds: [],
    },
    courseIds: ["crs-1", "crs-2"],
    targetRoles: [
      "Junior Software Engineer",
      "Full-Stack Web Developer",
      "AI Solutions Engineer",
    ],
  },
];

// ─── Decoupled Progress Records Store ───────────────────────────────────────

export const MOCK_PROGRESS: LearningProgress[] = [
  {
    id: "prog-1",
    userId: "usr-student-demo",
    entityId: "trk-1",
    entityType: "track",
    status: "in_progress",
    scorePercentage: 68,
    timeSpentSeconds: 28800,
    lastAccessedAt: "2026-08-01T10:00:00Z",
    startedAt: "2026-01-10T10:00:00Z",
  },
  {
    id: "prog-2",
    userId: "usr-student-demo",
    entityId: "crs-1",
    entityType: "course",
    status: "completed",
    scorePercentage: 100,
    timeSpentSeconds: 18000,
    lastAccessedAt: "2026-07-28T15:30:00Z",
    startedAt: "2026-01-10T10:00:00Z",
    completedAt: "2026-07-28T15:30:00Z",
    verifiedAt: "2026-07-29T09:00:00Z",
    verifiedBy: "usr-mentor-1",
  },
  {
    id: "prog-3",
    userId: "usr-student-demo",
    entityId: "les-1",
    entityType: "lesson",
    status: "completed",
    scorePercentage: 98,
    timeSpentSeconds: 1500,
    lastAccessedAt: "2026-07-20T11:00:00Z",
    startedAt: "2026-01-10T10:00:00Z",
    completedAt: "2026-07-20T11:00:00Z",
  },
];
